# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pay With Friends' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pay With Friends
  pod 'NavKit', '~> 0.5'

end
